data:
  dataset:
    seed: 123
    max_num_res: 512
    cache_num_res: 0
    min_num_res: 60
    subset: null
    generate_valid_samples: true
    samples_per_eval_length: 10
    num_eval_lengths: 8
    min_eval_length: 300
    train_valid_test_split:
    - 1.0
    - 0.0
    - 0.0
    csv_path: ./metadata_nobreaks_pkl.csv
    filter_breaks: true
    scrmsd_csv_path: null
    filter_scrmsd: 'inf'
    flexibility: true
    calc_dssp: true
    target_sec_content:
      helix_percent: 0.39
      strand_percent: 0.21
    extra_features:
    - local_flex
  loader:
    num_workers: 4
    prefetch_factor: 10
  sampler:
    max_batch_size: 100
    max_num_res_squared: 500000
    clustered: false
experiment:
  debug: false
  use_wandb: true
  use_tqdm: false
  seed: 123
  num_devices: 8
  warm_start: ./sec_dev:0.11-epoch:6904.ckpt
  warm_start_cfg_override: true
  use_swa: false
  first_val_epoch: 6904
  batch_ot:
    enabled: true
    cost: kabsch
    noise_per_sample: 1
  training:
    min_plddt_mask: null
    loss: se3_vf_loss
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_t_pass: 0.75
    t_bins: 5
  wandb:
    name: gafl-flex_gpus8_6904_warm
    project: gafl-flex
    save_dir: outputs/
    tags: []
  optimizer:
    lr: 0.0001
  reset_optimizer_on_load: false
  warmup_lr: false
  warmup_lr_factor: 0.01
  trainer:
    overfit_batches: 0
    min_epochs: 1
    max_epochs: 10000000
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: false
    strategy: ddp
    check_val_every_n_epoch: 2
    default_root_dir: outputs/
    accumulate_grad_batches: 1
  checkpointer:
    dirpath: outputs/ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: true
    filename: epoch:{epoch:03d}
    every_n_epochs: 2
    save_top_k: -1
    auto_insert_metric_name: false
  checkpointer2:
    dirpath: outputs/ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: false
    filename: sec_dev:{sec_deviation:.2f}-epoch:{epoch:03d}
    save_top_k: 15
    monitor: valid/sec_deviation
    mode: min
    every_n_epochs: 2
    first_epoch: ${experiment.first_val_epoch}
    auto_insert_metric_name: false
  profiler:
    enabled: false
    modules: null
    profile:
      use_cuda: true
      with_stack: false
    stats:
      group_by_stack_n: 0
      group_by_input_shapes: false
      prefixes:
      - 'layer_0::'
      - 'layer_1::'
      sort_by: cpu_time_total
  flexibility:
    flag: true
    mask_prob:
    - 0.1
    - 0.0
    - 0.9
    max_window_size: 0.4
    min_window_size: 0.2
    predictor_path: 'null'
    output_dir: outputs/flex_inference/
    aux_loss_weight: 100.0
    aux_loss_min_time: 0
  motif_scaffolding:
    flag: false
    mask_prob:
    - 0.8
    - 0.2
    min_size: 0.05
    max_size: 0.5
interpolant:
  min_t: 0.01
  t_interval:
  - 0.0
  - 1.0
  rots:
    train_schedule: linear
    sample_schedule: exp
    exp_rate: 10
  trans:
    train_schedule: linear
    sample_schedule: linear
  sampling:
    num_timesteps: 100
  self_condition: ${model.edge_features.self_condition}
  noise_res_scaling_power: 0.0
  noise_scale: 1.0
model:
  module: models.gafl.flow_model_final.FlowModel
  node_embed_size: 240
  edge_embed_size: 120
  symmetric: false
  node_features:
    c_s: 240
    c_pos_emb: 120
    c_timestep_emb: 120
    embed_diffuse_mask: false
    max_num_res: 2000
    timestep_int: 1000
    total_length_emb_dim: 0
    total_flex_emb_dim: 8
  edge_features:
    single_bias_transition_n: 2
    c_s: 240
    c_p: 120
    relpos_k: 64
    use_rbf: true
    num_rbf: 32
    feat_dim: 64
    num_bins: 22
    self_condition: true
  gfa:
    c_s: 240
    c_z: 120
    c_hidden: 120
    no_heads: 8
    no_qk_points: 8
    no_v_points: 8
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6
    readout_c_hidden: 32
